const hotelDetails = [
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food9.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "rice",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food8.jpg",
    discount: 28,
    ratings: 4,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food1.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food2.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food3.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food4.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food5.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food6.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
  {
    title: "Ugali",
    description: "lorem lorem lorem lorem lorem lorem",
    image: "./images/food7.jpg",
    discount: 20,
    ratings: 5,
    price: 300,
  },
];
